version: '3'

services:
  db:
    image: postgres
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    command: python3 project/manage.py runserver 0.0.0.0:8000
    volumes:  
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:  
      - .:/usr/src/app
